name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: input
    id: libversion
    attributes:
      label: Library Version
      description: Which version of Parquet.Net is affected?
      placeholder: ex. 4.5.1
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      description: Which OS is this affecting?
      placeholder: ex. Ubuntu Linux
    validations:
      required: true
