name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: input
    id: libversion
    attributes:
      label: Library Version
      description: Which version of Parquet.Net is affected?
      placeholder: ex. 4.5.1
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      description: Which OS is this affecting?
      placeholder: ex. Ubuntu Linux
    validations:
      required: true
  - type: dropdown
    id: os-arch
    attributes:
      label: OS Architecture
      description: OS Architecture
      options:
        - 32 bit
        - 64 bit
        - ARM 64
        - Other (please specify)
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: How to reproduce?
      description: Exact steps to reproduce this bug.
      value: "1. ...."
    validations:
      required: true
  - type: textarea
    id: repro-code
    attributes:
      label: Failing test
      description: Providing a failing unit test or runnable piece of code will greatly speed up issue resolution.
      value: ""
      render: csharp
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true