name: General Issue
description: NOT a bug report.
title: "XXX"
labels: [ "bug" ]
assignees:
  - octocat
body:
  - type: textarea
    id: text
    attributes:
      label: Issue description
      description: Please describe the issue.
      value: "1. ...."
    validations:
      required: true